version: 2
jobs:
  build:
    docker:
      - image: circleci/node:20.11.1
    steps:
      - checkout
      - run:
          name: Install Dependencies in My_bland
          environment:
            TEST_USER_NAME: TEST_USER_NAME
            TEST_KEY: TEST_KEY
            TEST_COLLECTION_NAME: TEST_COLLECTION_NAME
          command: npm install
      - run:
          name: Testing apis
          command: npm test
